#spring.application.name=TicketingPlatform

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/C:/TicketingPlatformDB/test;MODE=MYSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true # h2-console 요청이 시큐리티 필터를 통과하지 않도록 설정

  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

  sql:
    init:
      encoding: UTF-8

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

